#!/bin/sh -e
#
# Build the kiosk.  Needs to be run as root.
#
# Originally based loosely on the following:
# https://michaelwiki.geekgalaxy.com/index.php/Web_Kiosk_CentOS_7
#

# Configurables

ACCOUNT=kiosk
AUTOLOGIN_TTY=tty1
KIOSK_URL="https://192.168.1.50/frontend/5"

# End configurables


if [ "$(id -u)" != "0" ]
then
    echo "Must be run as root." 1>&2
    exit 1
fi


#
# Basic setup and packages
#

yum -y update
yum -y install epel-release
yum makecache

yum -y install \
    chromium \
    htop \
    nano \
    smartmontools \
    wget \
    xorg-x11-drv-\* \
    xorg-x11-fonts-\* \
    liberation-\* \
    xorg-x11-server-Xorg \
    xorg-x11-utils \

yum -y group install Xfce


#
# User Account
#

useradd "${ACCOUNT}"
ACCOUNT_HOME=$(awk -v "ACCT=${ACCOUNT}" -F: '$1 == ACCT { print $6 }' \
    /etc/passwd)


#
# Autologin on ${AUTOLOGIN_TTY}
#

rm -f "/etc/systemd/system/getty.target.wants/getty@${AUTOLOGIN_TTY}.service"

cp \
    /lib/systemd/system/getty@.service \
    "/etc/systemd/system/getty@${AUTOLOGIN_TTY}.service"

sed -i -e "s/\/sbin\/agetty/\0 --autologin ${ACCOUNT}/" \
    "/etc/systemd/system/getty@${AUTOLOGIN_TTY}.service"

ln -s "/etc/systemd/system/getty@${AUTOLOGIN_TTY}.service" \
    "/etc/systemd/system/getty.target.wants/getty@${AUTOLOGIN_TTY}.service"

cat << EOF >> "${ACCOUNT_HOME}/.bash_profile"
if [[ -z \$DISPLAY ]] && [[ \$(tty) = /dev/${AUTOLOGIN_TTY} ]]; then
    startx
else
    echo "Not started on ${AUTOLOGIN_TTY}; not running X."
fi
EOF



cat << EOF >> "${ACCOUNT_HOME}/.xinitrc"
#!/bin/sh

exec startxfce4
EOF


#
# Unclutter - Gets rid of the mouse pointer
#

wget -O unclutter.tar https://www.archlinux.org/packages/community/x86_64/unclutter/download/
tar -xf unclutter.tar
mv usr/bin/unclutter /usr/bin/unclutter
chown root.root /usr/bin/unclutter
chmod 755 /usr/bin/unclutter
rm -rf usr

cat << EOF >>/etc/xdg/autostart/unclutter.desktop
[Desktop Entry]
Encoding=UTF-8
Name=Kiosk
GenericName=program
Comment=Kiosk
Exec=unclutter -grab
Icon=/usr/share/pixmaps/program.jpg
Terminal=false
Type=Application
Categories=
OnlyShowIn=XFCE;
EOF



#
# Script to run Chromium cleanly
#

cat << EOF >> "${ACCOUNT_HOME}/run-chromium"
#!/bin/sh

sleep 10

# Do everything repeatedly

while true
do

    xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/dpms-enabled -s false
    xset -dpms
    xset s noblank
    xset s off
    xset s 0

    # Start with a clean slate every time.
    rm -rf "\${HOME}/.config/chromium"

    # Full list of command-line switches:
    # https://peter.sh/experiments/chromium-command-line-switches/
    chromium-browser \
        --allow-running-insecure-content \
        --disable-infobars \
        --ignore-certificate-errors \
        --kiosk \
        --noerrdialogs \
        --no-first-run \
        --password-store=basic \
        "${KIOSK_URL}"

done
EOF
chmod +x "${ACCOUNT_HOME}/run-chromium"


cat << EOF >> /etc/xdg/autostart/chromium.desktop
[Desktop Entry]
Encoding=UTF-8
Name=Kiosk
GenericName=program
Comment=Chromium
Exec=${ACCOUNT_HOME}/run-chromium
Icon=/usr/share/pixmaps/program.jpg
Terminal=false
Type=Application
Categories=
OnlyShowIn=XFCE;
EOF



#
# Get rid of desktop stuff
#

SESSION="/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml"
rm -f "${SESSION}"
cat << EOF > "${SESSION}"
<?xml version="1.0" encoding="UTF-8"?>

<channel name="xfce4-session" version="1.0">
  <property name="general" type="empty">
    <property name="FailsafeSessionName" type="string" value="Failsafe"/>
  </property>
  <property name="sessions" type="empty">
    <property name="Failsafe" type="empty">
      <property name="IsFailsafe" type="bool" value="true"/>
      <property name="Count" type="int" value="5"/>
      <property name="Client0_Command" type="array">
        <value type="string" value="xfwm4"/>
      </property>
    </property>
  </property>
  <property name="splash" type="empty">
    <property name="Engine" type="string" value=""/>
  </property>
</channel>
EOF



#
# Disable as much power management as possible
#

PFCE="${ACCOUNT_HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
mkdir -p $(dirname "${PFCE}")
cat << EOF >> "${PFCE}"
<?xml version="1.0" encoding="UTF-8"?>

<channel name="xfce4-power-manager" version="1.0">
  <property name="xfce4-power-manager" type="empty">
    <property name="power-button-action" type="uint" value="4"/>
    <property name="sleep-button-action" type="uint" value="3"/>
    <property name="hibernate-button-action" type="uint" value="3"/>
    <property name="show-tray-icon" type="bool" value="false"/>
    <property name="lock-screen-suspend-hibernate" type="bool" value="false"/>
    <property name="lid-action-on-battery" type="uint" value="1"/>
    <property name="logind-handle-lid-switch" type="bool" value="false"/>
    <property name="lid-action-on-ac" type="uint" value="1"/>
    <property name="blank-on-ac" type="uint" value="0"/>
  </property>
</channel>
EOF




#
# Make sure everything in the account is owned by the account
#

chown -R "${ACCOUNT}.${ACCOUNT}" "${ACCOUNT_HOME}"


#
# Force all Ethernet interfaces to enabled on boot
#

find /etc/sysconfig/network-scripts -name "ifcfg-*" \
    | xargs egrep -l "TYPE=Ethernet" \
    | xargs -r sed -i -e 's/ONBOOT=no/ONBOOT=yes/g'


#
# Clean out some cruft
#

# YUM leftovers we won't need
yum clean all
rm -rf /var/cache/yum

# No swap; we'll have enough RAM
swapoff /swapfile
sed -i -e '/\/swapfile/d' /etc/fstab
rm -f /swapfile


#
# Shut 'er down.
#
echo
echo Powering off.
echo
poweroff
